### PR TITLE
new staging host for node-pre-gyp

### PR DESCRIPTION
**Pull request by bmacnaughton**
- used rc-files-t2/nodejs/bindings for staging
- use released version of node-pre-gyp (1.0.0-alpha2)

### CODE REVIEW

**Review by prettycoder — COMMENTED** [review]
2 questions:

- these are S3 buckets, should they be labelled `staging_bucket` or is the name `staging_host` a requirement

- How about the Production host? is it possible to rename the bucket, so it says `node` instead of `bruce` ... ? It sounds like a personal bucket, I think a less personal name would help to avoid confusion.

**Comment by bmacnaughton** [comment]
the names `staging_host` and `production_host` are determined by `node-pre-gyp`. the reason for that (i wrote that code) is that one of them is used to fill in the `host` field which is has been in use for a long time.

`production_host` is going to change. i'm going to leave it where it is not to facilitate testing but it will change before production. end users can look at the values but never use them.

**Comment by prettycoder** [comment]
first answer makes sense, second one is a bit confusing. 

- When will it change? 
- What does it mean it will change before production?
- I'm less worried about the name in the script, but the bucket in S3, which, once no Bruce is around the team anymore, may get deleted.

**Review by prettycoder — APPROVED** [review]
thanks for the explanations
lgtm :)

**Pull request merged**
